/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thuvien.classes.ThuVien.ui;

import javax.swing.ImageIcon;
import thuvien.classes.ThuVien.dao.GiaoVienDAO;
import thuvien.classes.ThuVien.entity.GiaoVien;
import thuvien.classes.ThuVien.helper.Auth;
import static thuvien.classes.ThuVien.helper.MsgBox.alert;

/**
 *
 * @author QUOC DAO
 */
public class DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    static boolean isManager;
    boolean showPass = false;
    
    public DangNhap() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnDangNhap = new javax.swing.JButton();
        txtMatKhau = new javax.swing.JPasswordField();
        lblAn_Hien = new javax.swing.JLabel();
        txtBackgound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblId.setText("Mã ID");
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        lblMatKhau.setText("Mật Khẩu");
        jPanel1.add(lblMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 180, -1));

        btnDangNhap.setText("Đăng Nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        jPanel1.add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));
        jPanel1.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 180, -1));

        lblAn_Hien.setForeground(new java.awt.Color(255, 255, 255));
        lblAn_Hien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thuvien/classes/ThuVien/images/HienMatKhau.png"))); // NOI18N
        lblAn_Hien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAn_HienMousePressed(evt);
            }
        });
        jPanel1.add(lblAn_Hien, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        txtBackgound.setBackground(new java.awt.Color(255, 255, 255));
        txtBackgound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thuvien/classes/ThuVien/images/DangNhap4.png"))); // NOI18N
        jPanel1.add(txtBackgound, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAn_HienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAn_HienMousePressed
       if (showPass == false) {
            txtMatKhau.setEchoChar((char) 0);
            lblAn_Hien.setIcon(new ImageIcon("src/thuvien/classes/ThuVien/images/AnMatKhau.png"));
            showPass = true;
        } else {
            txtMatKhau.setEchoChar('*');
            lblAn_Hien.setIcon(new ImageIcon("src/thuvien/classes/ThuVien/images/HienMatKhau.png"));
            showPass = false;
        }
    }//GEN-LAST:event_lblAn_HienMousePressed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        if (kiemTra()) {
                
            new GiaoDien().setVisible(true);
            this.dispose();
            }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    GiaoVienDAO dao = new GiaoVienDAO();
    
    public boolean kiemTra() {
        if (txtId.getText().equals("") && String.valueOf(txtMatKhau.getPassword()).equals("")) {
            alert(this, "Xin hãy nhập tên đăng nhập và mật khẩu.");
            txtId.requestFocus();
            return false;
        } else if (txtId.getText().equals("")) {
            alert(this, "Bạn chưa nhập tên đăng nhập.");
            txtId.requestFocus();
        } else if (String.valueOf(txtMatKhau.getPassword()).equals("")) {
            alert(this, "Bạn chưa nhập mật khẩu.");
            txtMatKhau.requestFocus();
            return false;
        }
        return true;
    }

    public void dangNhap() {
        String tendangnhap = txtId.getText();
        String matkhau = String.valueOf(txtMatKhau.getPassword());
        GiaoVien giaoVien = dao.selectById(tendangnhap);
        if (giaoVien == null) {
            alert(this, "Tên đăng nhập không đúng.");
        } else if (!matkhau.equals(giaoVien.getMatKhau())) {
            alert(this, "Mật khẩu không đúng.");
        } else {
            Auth.user = giaoVien;
            this.dispose();
            new GiaoDien().setVisible(true);

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAn_Hien;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel txtBackgound;
    private javax.swing.JTextField txtId;
    private javax.swing.JPasswordField txtMatKhau;
    // End of variables declaration//GEN-END:variables
}
