/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thuvien.classes.ThuVien.ui;

import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import thuvien.classes.ThuVien.dao.GiaoVienDAO;
import thuvien.classes.ThuVien.helper.MsgBox;

/**
 *
 * @author QUOC DAO
 */
public class PanelGiaoVien extends javax.swing.JPanel {

    /**
     * Creates new form GiaoVien
     */
    public PanelGiaoVien() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgGioiTinh = new javax.swing.ButtonGroup();
        btnLamMoi = new javax.swing.JButton();
        lblMaGV = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGiaoVien = new javax.swing.JTable();
        txtMaGV = new javax.swing.JTextField();
        lblHoTenGV = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        txtHoTenGV = new javax.swing.JTextField();
        btnLast = new javax.swing.JButton();
        lblMatKhau = new javax.swing.JLabel();
        btnFirst = new javax.swing.JButton();
        lblGioiTinh = new javax.swing.JLabel();
        btnPrev = new javax.swing.JButton();
        rdoNam = new javax.swing.JRadioButton();
        txtMatKhau = new javax.swing.JTextField();
        rdoNu = new javax.swing.JRadioButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thuvien/classes/ThuVien/images/Icon_24px/Update.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        lblMaGV.setText("Mã giáo viên");

        tblGiaoVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã GV", "Họ tên GV", "Giới tính", "Mật khẩu"
            }
        ));
        jScrollPane2.setViewportView(tblGiaoVien);

        lblHoTenGV.setText("Họ tên giáo viên");

        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        lblMatKhau.setText("Mật khẩu");

        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        lblGioiTinh.setText("Giới tính");

        btnPrev.setText("<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btgGioiTinh.add(rdoNam);
        rdoNam.setText("Nam");

        btgGioiTinh.add(rdoNu);
        rdoNu.setText("Nữ");

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thuvien/classes/ThuVien/images/Icon_24px/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thuvien/classes/ThuVien/images/Icon_24px/Edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaGV)
                    .addComponent(txtMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoTenGV)
                    .addComponent(txtHoTenGV, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGioiTinh)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdoNam)
                        .addGap(7, 7, 7)
                        .addComponent(rdoNu))
                    .addComponent(lblMatKhau)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btnFirst)
                .addGap(9, 9, 9)
                .addComponent(btnPrev)
                .addGap(9, 9, 9)
                .addComponent(btnNext)
                .addGap(9, 9, 9)
                .addComponent(btnLast)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnLamMoi)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMaGV)
                        .addGap(9, 9, 9)
                        .addComponent(txtMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(lblHoTenGV)
                        .addGap(9, 9, 9)
                        .addComponent(txtHoTenGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(lblGioiTinh)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoNam)
                            .addComponent(rdoNu))
                        .addGap(12, 12, 12)
                        .addComponent(lblMatKhau)
                        .addGap(9, 9, 9)
                        .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFirst)
                    .addComponent(btnPrev)
                    .addComponent(btnNext)
                    .addComponent(btnLast)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnLamMoi))
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        clearForm();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        isUpdate = false;
        if (checkForm()) {
            insert();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        isUpdate = true;
        if (checkForm()) {
            Update();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    JTableHeader header;
    boolean isUpdate = false;
    DefaultTableModel model;
    GiaoVienDAO dao = new GiaoVienDAO();
    int row = -1;
    
    public void setModelTable() {
        model = new DefaultTableModel(new Object[][]{}, new Object[]{"Mã giáo viên", "Họ tên giáo viên", "Giới tính", "Mật khẩu"});
        tblGiaoVien.setModel(model);
        header = tblGiaoVien.getTableHeader();
        header.setFont(new Font("SansSerif", 1, 12));
        header.setForeground(new Color(0, 0, 0));
        tblGiaoVien.setForeground(new Color(0, 0, 0));
    }
    
    public void init() {
        setModelTable();
        fillTable();
    }


    public void insert() {
        thuvien.classes.ThuVien.entity.GiaoVien gv = getForm();
        try {
            dao.insert(gv);
            fillTable();
            clearForm();
            JOptionPane.showMessageDialog(this, "thêm thành công");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "thêm thất bại");
        }
    }

    public void Update() {
        thuvien.classes.ThuVien.entity.GiaoVien gv = getForm();
        if (MsgBox.confirm(this, "Bạn có chắc muốn cập nhật không?")) {
            try {
                dao.update(gv);
                fillTable();
                clearForm();
                JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
            }
        }

    }

    public void first() {
        row = 0;
        tblGiaoVien.setRowSelectionInterval(row, row);
        edit();
    }

    public void next() {
        if (row < tblGiaoVien.getRowCount() - 1) {
            row++;
            tblGiaoVien.setRowSelectionInterval(row, row);
            edit();
        }
    }

    public void prev() {
        if (row > 0) {
            row--;
            tblGiaoVien.setRowSelectionInterval(row, row);
            edit();
        }
    }

    public void last() {
        row = tblGiaoVien.getRowCount() - 1;
        tblGiaoVien.setRowSelectionInterval(row, row);
        edit();
    }

    public void updateStatus() {
        boolean edit = (row >= 0);
        boolean first = (row == 0);
        boolean last = (row == tblGiaoVien.getRowCount() - 1);
        //trạng thái form
        txtMaGV.setEditable(!edit);
        btnThem.setEnabled(!edit);
        btnSua.setEnabled(edit);

//        txtMaGV.setText(Auth.user.getMaGV());
    }

    public thuvien.classes.ThuVien.entity.GiaoVien setForm(thuvien.classes.ThuVien.entity.GiaoVien gv) {
        txtMaGV.setText(gv.getMaGV());
        txtHoTenGV.setText(gv.getHoTenGV());
        //txtNgaySinh.setText(String.valueOf(nh.getNgaySinh()));
        if (gv.getGioiTinh() == true) {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
        txtMatKhau.setText(gv.getMatKhau());
        return gv;
    }

    public thuvien.classes.ThuVien.entity.GiaoVien getForm() {
        thuvien.classes.ThuVien.entity.GiaoVien gv = new thuvien.classes.ThuVien.entity.GiaoVien();
        gv.setMaGV(txtMaGV.getText());
        gv.setHoTenGV(txtHoTenGV.getText());
        if (rdoNam.isSelected()) {
            gv.setGioiTinh(true);
        } else {
            gv.setGioiTinh(false);
        }
        gv.setMatKhau(txtMatKhau.getText());
        return gv;
    }

    public void clearForm() {
        thuvien.classes.ThuVien.entity.GiaoVien gv = new thuvien.classes.ThuVien.entity.GiaoVien();
        setForm(gv);
        txtMaGV.setText("");
        txtHoTenGV.setText("");
        txtMatKhau.setText("");
        btgGioiTinh.clearSelection();

        row = -1;
        updateStatus();
    }

    public void edit() {
        String manh = String.valueOf(tblGiaoVien.getValueAt(row, 0));
        thuvien.classes.ThuVien.entity.GiaoVien gv = dao.selectById(manh);
        setForm(gv);
        updateStatus();
    }

    public void fillTable() {
        model.setRowCount(0);
        try {
            List<thuvien.classes.ThuVien.entity.GiaoVien> list = dao.selectAll(); // Error!
            
            for (thuvien.classes.ThuVien.entity.GiaoVien gv : list) {
                Object[] row = {gv.getMaGV(), gv.getHoTenGV(), gv.getGioiTinh() ? "Nam" : "Nữ", gv.getMatKhau()};
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public boolean checkForm() {
        if (txtMaGV.getText().equals("") && txtHoTenGV.getText().equals("") || txtMatKhau.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Xin hãy nhập đủ dữ liệu sau đó ấn Thêm", "Error", 1);
            return false;
        } else if (txtHoTenGV.getText().equals("")) {
            MsgBox.alert(this, "Vui lòng nhập đầy đủ họ tên!");
            txtHoTenGV.requestFocus();
            return false;
        } else if (txtMatKhau.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mật khẩu");
            txtMatKhau.requestFocus();
            return false;
        }
        List<thuvien.classes.ThuVien.entity.GiaoVien> list = dao.selectAll();
        for (int i = 0; i < list.size(); i++) {
            if (isUpdate) {
            } else {
                if (txtMaGV.getText().equalsIgnoreCase(list.get(i).getMaGV())) {
                    JOptionPane.showMessageDialog(this, "Trùng Mã Giáo viên", "Error", 1);
                    return false;
                }
            }
        }

        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgGioiTinh;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHoTenGV;
    private javax.swing.JLabel lblMaGV;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblGiaoVien;
    private javax.swing.JTextField txtHoTenGV;
    private javax.swing.JTextField txtMaGV;
    private javax.swing.JTextField txtMatKhau;
    // End of variables declaration//GEN-END:variables
}
